/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const FourChoiceLazyRouteImport = createFileRoute('/four-choice')()
const ConfigLazyRouteImport = createFileRoute('/config')()
const AboutLazyRouteImport = createFileRoute('/about')()
const IndexLazyRouteImport = createFileRoute('/')()

const FourChoiceLazyRoute = FourChoiceLazyRouteImport.update({
  id: '/four-choice',
  path: '/four-choice',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/four-choice.lazy').then((d) => d.Route))
const ConfigLazyRoute = ConfigLazyRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/config.lazy').then((d) => d.Route))
const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/config': typeof ConfigLazyRoute
  '/four-choice': typeof FourChoiceLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/config': typeof ConfigLazyRoute
  '/four-choice': typeof FourChoiceLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/config': typeof ConfigLazyRoute
  '/four-choice': typeof FourChoiceLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/config' | '/four-choice'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/config' | '/four-choice'
  id: '__root__' | '/' | '/about' | '/config' | '/four-choice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  ConfigLazyRoute: typeof ConfigLazyRoute
  FourChoiceLazyRoute: typeof FourChoiceLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/four-choice': {
      id: '/four-choice'
      path: '/four-choice'
      fullPath: '/four-choice'
      preLoaderRoute: typeof FourChoiceLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  ConfigLazyRoute: ConfigLazyRoute,
  FourChoiceLazyRoute: FourChoiceLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
